name: upload-wheel
on:
  push:
    tags:
      - 'v0.*'
  workflow_dispatch:
    inputs:
      tag:
        required: True
        description: 'Release tag'
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - run: echo ${{ github.event.push.tag }}
      - run: echo ${{ inputs.tag }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.tag }} ${{ inputs.tag }}
      - run: git describe --tags
