name: upload-wheel
on:
  push:
    tags:
      - 'v0.*'
  workflow_dispatch:
    inputs:
      tag:
        required: True
        description: 'Release tag'
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TAG: ${{ github.event.push.tag || github.event.inputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Check out the newly oushed tag or the tag specified in the
          # workflow dispatch. This works because only one variable is
          # set depending on how the workflow is triggered.
          ref: ${{ env.TAG }}
      - run: git describe --tags
