name: upload-wheel
on:
  push:
    tags:
      - 'v0.*'
  workflow_dispatch:
    inputs:
      tag:
        required: True
        description: 'Release tag'
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      # Only one of the variables is set.
      TAG: ${{ github.event.push.tag }} ${{ github.event.inputs.tag }}
    steps:
      - run: echo "$TAG"
      - run: [[ "$TAG" =~ '^v[0-9]+.[0-9]+.[0-9]+' ]]
      - uses: actions/checkout@v2
        with:
          # Check out the newly oushed tag or the tag specified in the
          # workflow dispatch. This works because
          ref:
      - run: git describe --tags
