name: upload-wheel
on:
  push:
    tags:
      - 'v0.*'
  workflow_dispatch:
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.tag }}
      - run: git describe --tags
