name: upload-wheel
on:
  push:
    tags:
      - '2.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Release'
jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.6', '3.7', '3.8', '3.9', '3.10']
        os: [windows, macos]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.push.tag }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install wheel twine
      - run: python setup.py bdist_wheel
      - run: twine upload dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
